Support libc.so.6.1
allisonkarlitskaya/ferny pull request #32
Opened 2024-12-12 07:49 UTC by martinpitt

This is the SONAME on ia64/alpha.

See https://github.com/cockpit-project/cockpit/issues/21396

2024-12-12 07:49 UTC, martinpitt commented
There are no porter boxes for these two arches. I tested this on x86 by flipping the imports, i.e. trying to import 6.1 first.

2024-12-13 08:33 UTC, allisonkarlitskaya commented
ia64 and alpha?  srsly?

2024-12-13 08:36 UTC, allisonkarlitskaya requested changes

2024-12-13 08:36 UTC, allisonkarlitskaya commented on src/ferny/session.py
> +    prctl = ctypes.cdll.LoadLibrary('libc.so.6').prctl
I think you can just `ctypes.CDLL(None)` for this...

2024-12-13 08:43 UTC, martinpitt commented
ia64 got scrapped, but [alpha is still a thing](https://buildd.debian.org/status/package.php?p=cockpit) ...

Thanks for the hint! Done.

2024-12-13 08:48 UTC, allisonkarlitskaya approved these changes

2024-12-13 08:49 UTC, merged